---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: client
  label: client
- type: text
  name: about
  label: about
- type: text
  name: tags
  label: tags
- type: text
  name: project-url
  label: project-url
