---
label: Project
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: Title
- name: tags
  type: tag_list
  default:
  - Wvd
  - School
  - Print
  - Sign
  - Branding
  - Online
  - Fotografie
  - Web
  label: Tags
- type: text
  name: client
  label: Client
- type: text
  name: project-url
  label: Project link
  description: Url to project
- name: ft-img
  type: file
  config:
    maxSize: 250
  label: Featured image
- name: galery
  type: image_gallery
  config: {}
  label: Gallerij
pages:
- _projects/kampaandenken-wolokamp-18.md
- _projects/geboortekaart-igor.md
- _projects/the-docks.md
- _projects/hotel-iconografie.md
- _projects/koleur-gantoise.md
- _projects/the-bicycle-shop.md
- _projects/open-scouts-weekend-16.md
- _projects/personal-startpage.md
