---
label: Project
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: Title
- type: text
  name: client
  label: Client
- type: text
  name: project-url
  label: Project link
  description: Url to project
- name: ft-img
  type: file
  config:
    maxSize: 250
  label: Featured image
- name: tags
  type: select
  default: ''
  config:
    required: false
    options:
    - Web
    - School
    - Fotografie
    - WVD
    - Print
    - Sign
    - Online
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Tags
pages:
- _projects/personal-startpage.md
